# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 402 IS Travel Wiki
email: madeline.hundley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The 402 IS Travel Wiki is a place to share travel stories and tips.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.402-is-travel.com" # the base hostname & protocol for your site
github_username:  madhundle

# Build settings
markdown: kramdown
